// Generated by tools/gen_header.py -- do not edit.
// Source: circuits/ain_224.cir + circuits/aout_224.cir via tools/mna.py --audio-fit
#pragma once
#include "analog.hpp"
namespace lexicon224x::analog {
inline Modal ain_224_modal() {
    Modal m;
    m.poles.push_back({-30303.16922232196, 86598.07360509051});
    m.residues.push_back({-1535.566601095282, -303.913252204529});
    m.poles.push_back({-30303.16922232196, -86598.07360509051});
    m.residues.push_back({-1535.566601095282, 303.913252204529});
    m.poles.push_back({-2079.01966805843, 52657.713571139124});
    m.residues.push_back({-747.0265644510486, 11863.594897528039});
    m.poles.push_back({-2079.01966805843, -52657.713571139124});
    m.residues.push_back({-747.0265644510486, -11863.594897528039});
    m.poles.push_back({-7591.824267460196, 47083.68694027513});
    m.residues.push_back({-18171.93448936985, -43128.62144416562});
    m.poles.push_back({-7591.824267460196, -47083.68694027513});
    m.residues.push_back({-18171.93448936985, 43128.62144416562});
    m.poles.push_back({-16515.629520320686, 30674.000189746792});
    m.residues.push_back({46300.222444901585, 86311.59842586887});
    m.poles.push_back({-16515.629520320686, -30674.000189746792});
    m.residues.push_back({46300.222444901585, -86311.59842586887});
    m.poles.push_back({-39606.34650559455, 0.0});
    m.residues.push_back({-142926.05668907412, 0.0});
    m.poles.push_back({-22721.559324947593, 0.0});
    m.residues.push_back({91234.66712059393, 0.0});
    m.direct = -1.9027652288899368e-11;
    m.scale = 0.6714903705341165;
    return m;
}
inline Modal aout_224_modal() {
    Modal m;
    m.poles.push_back({-499999.92763972917, 0.0});
    m.residues.push_back({-3.3357989152375994e-05, 0.0});
    m.poles.push_back({-2078.9309743031404, 52656.156156557365});
    m.residues.push_back({-154.75983466442128, -521.1939205999234});
    m.poles.push_back({-2078.9309743031404, -52656.156156557365});
    m.residues.push_back({-154.75983466442128, 521.1939205999234});
    m.poles.push_back({-7593.720389659135, 47085.12790844678});
    m.residues.push_back({1802.026900585217, 1082.4614462112024});
    m.poles.push_back({-7593.720389659135, -47085.12790844678});
    m.residues.push_back({1802.026900585217, -1082.4614462112024});
    m.poles.push_back({-16514.177328627768, 30674.64428732316});
    m.residues.push_back({-4855.783307439754, 1742.6454306668868});
    m.poles.push_back({-16514.177328627768, -30674.64428732316});
    m.residues.push_back({-4855.783307439754, -1742.6454306668868});
    m.poles.push_back({-22720.857808301902, 0.0});
    m.residues.push_back({-9549.660499129033, 0.0});
    m.poles.push_back({-2.0328722285876513, 0.0});
    m.residues.push_back({-1.274430980922891, 0.0});
    m.poles.push_back({-12550.2093589853, 0.0});
    m.residues.push_back({16073.03221843225, 0.0});
    m.direct = 3.5966000160032862e-12;
    m.scale = 1.5975062688498582;
    return m;
}
}  // namespace lexicon224x::analog
