// Generated by tools/gen_header.py -- do not edit.
// Source: circuits/ain_224x.cir + circuits/aout_224x.cir via tools/mna.py --audio-fit
#pragma once
#include "analog.hpp"
namespace lexicon224x::analog {
inline Modal ain_modal() {
    Modal m;
    m.poles.push_back({-45454.75388750916, 129897.11080552098});
    m.residues.push_back({599.773325965535, -9738.048963400382});
    m.poles.push_back({-45454.75388750916, -129897.11080552098});
    m.residues.push_back({599.773325965535, 9738.048963400382});
    m.poles.push_back({-4102.298527633177, 96728.4657975426});
    m.residues.push_back({-3115.5783052596125, 33527.28561804381});
    m.poles.push_back({-4102.298527633177, -96728.4657975426});
    m.residues.push_back({-3115.5783052596125, -33527.28561804381});
    m.poles.push_back({-14963.06197207162, 85999.19138571685});
    m.residues.push_back({-31892.933065639514, -132417.4931524734});
    m.poles.push_back({-14963.06197207162, -85999.19138571685});
    m.residues.push_back({-31892.933065639514, 132417.4931524734});
    m.poles.push_back({-34379.626801054466, 52026.47659924561});
    m.residues.push_back({15332.017538737677, 300041.418123026});
    m.poles.push_back({-34379.626801054466, -52026.47659924561});
    m.residues.push_back({15332.017538737677, -300041.418123026});
    m.poles.push_back({-79535.43774462046, 0.0});
    m.residues.push_back({-613178.6793615303, 0.0});
    m.poles.push_back({-7365.576561320724, 0.0});
    m.residues.push_back({-213.5380362124952, 0.0});
    m.poles.push_back({-55623.822331865085, 0.0});
    m.residues.push_back({651545.6581728631, 0.0});
    m.direct = 2.4950753693704976e-10;
    m.scale = 0.6768697179710966;
    return m;
}
inline Modal aout_modal() {
    Modal m;
    m.poles.push_back({-499999.9196412927, 0.0});
    m.residues.push_back({-0.014290779565073639, 0.0});
    m.poles.push_back({-3866.5136046706643, 98714.32890413406});
    m.residues.push_back({-285.32850305430486, -775.0280427752442});
    m.poles.push_back({-3866.5136046706643, -98714.32890413406});
    m.residues.push_back({-285.32850305430486, 775.0280427752442});
    m.poles.push_back({-14298.548643106906, 88288.04903327773});
    m.residues.push_back({2870.8837308856587, 1408.6510272456123});
    m.poles.push_back({-14298.548643106906, -88288.04903327773});
    m.residues.push_back({2870.8837308856587, -1408.6510272456123});
    m.poles.push_back({-30935.31584934812, 57688.25681141755});
    m.residues.push_back({-6993.1770747341725, 3525.780513937593});
    m.poles.push_back({-30935.31584934812, -57688.25681141755});
    m.residues.push_back({-6993.1770747341725, -3525.780513937593});
    m.poles.push_back({-42164.59294570152, 0.0});
    m.residues.push_back({-14122.997295322293, 0.0});
    m.poles.push_back({-2.0328722602013864, 0.0});
    m.residues.push_back({-1.2762189938663815, 0.0});
    m.poles.push_back({-19841.28472220363, 0.0});
    m.residues.push_back({23093.899981653653, 0.0});
    m.direct = 2.741597927047747e-09;
    m.scale = 1.5941996081501124;
    return m;
}
}  // namespace lexicon224x::analog
