#!/usr/bin/env python3
"""Write filters.hpp from modal JSON files (tools/mna.py --json).

  gen_header.py AIN.json AOUT.json OUT.hpp [--source TEXT] [--suffix _224]

--suffix names the functions ain{suffix}_modal / aout{suffix}_modal (the
Model 224's boards, filters_224.hpp, beside the 224X's filters.hpp).

Each chain is normalized to unit gain at 100 Hz (web 1.0 = 5 V at the ADC
on the input side; DAC full scale = 1.0 on the output side), so that levels
through the whole path are unchanged at low frequency; the emphasis and
filters shape everything above that.
"""
import json, sys
import numpy as np

def load(path):
    d = json.load(open(path))
    p = np.array([complex(*x) for x in d["poles"]]); r = np.array([complex(*x) for x in d["residues"]])
    s = 2j*np.pi*100
    g = abs(np.sum(r/(s-p)) + d["direct"])
    return p, r, d["direct"], 1.0/g

def emit(name, p, r, d, scale):
    lines = [f"inline Modal {name}() {{", "    Modal m;"]
    for pk, rk in zip(p, r):
        lines.append(f"    m.poles.push_back({{{float(pk.real)!r}, {float(pk.imag)!r}}});")
        lines.append(f"    m.residues.push_back({{{float(rk.real)!r}, {float(rk.imag)!r}}});")
    lines += [f"    m.direct = {float(d)!r};", f"    m.scale = {float(scale)!r};", "    return m;", "}"]
    return "\n".join(lines)

ain, aout, out = sys.argv[1:4]
options = dict(zip(sys.argv[4::2], sys.argv[5::2]))
source = options.get("--source", "tools/gen_header.py")
suffix = options.get("--suffix", "")
text = ["// Generated by tools/gen_header.py -- do not edit.", f"// Source: {source}", "#pragma once",
        '#include "analog.hpp"', "namespace lexicon224x::analog {",
        emit(f"ain{suffix}_modal", *load(ain)), emit(f"aout{suffix}_modal", *load(aout)), "}  // namespace lexicon224x::analog", ""]
open(out, "w").write("\n".join(text))
print(f"wrote {out}")
