// Firmware-set recognition, JUCE-free: the C++ twin of the web demo's
// web/firmware.js (findSets, describeSet) and page/larc.js (chipBase, modelOf),
// in ../../web-demo/page/.
//
// Known chips are recognized by their SHA-256 against the embedded
// firmware_sets.json (firmware_sets_data.hpp, generated by
// tools/gen_firmware_sets.py), whatever the files are named. Files that match
// no complete known set are placed by their names (SBCn, NVSn, ROMn) as one
// set of their own, "unrecognized chips (placed by name)", as the page does.
//
// Differences from the page, all defensive:
//   - a by-name chip whose base is negative ("SBC0") or that would run past
//     the 64 KiB address space is left out (the page would write out of bounds);
//   - \s in the name patterns is ASCII whitespace only.
//
// Bring your own ROM: nothing here holds chip bytes beyond the candidates the
// caller hands in.
#pragma once
#include "firmware_sets_data.hpp"
#include "sha256.hpp"
#include <algorithm>
#include <cctype>
#include <cstdint>
#include <map>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <vector>

namespace lexplug::roms {

// A file offered for recognition: its file name (no directories), where it
// came from (for messages), and its bytes.
struct Candidate {
    std::string name;
    std::string origin;
    std::vector<uint8_t> bytes;
};

struct Chip {
    unsigned base = 0;
    std::string sha256;
    std::string origin;
    std::vector<uint8_t> bytes;
};

struct RomSet {
    std::string name;
    int model = 0;                 // 0 = 224X/224XL, 1 = the original 224 (Engine's model)
    bool known = false;            // a complete set from firmware_sets.json
    bool supported = true;         // false: the row machine cannot run it
    std::string unsupported;       // why not, when !supported
    std::vector<Chip> chips;       // sorted by base
    std::string catalog_hash;      // 16 hex: page/catalogs/<hash>.json, share.js "fw"
};

inline constexpr const char *unrecognized_set_name = "unrecognized chips (placed by name)";
inline constexpr unsigned address_space = 0x10000;

namespace detail {

inline bool is_space(char c) {
    return c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f' || c == '\v';
}

inline bool is_digit(char c) {
    return c >= '0' && c <= '9';
}

// Does `word` (upper case) start at `at`, case-insensitively?
inline bool word_at(std::string_view text, size_t at, std::string_view word) {
    if (at + word.size() > text.size()) {
        return false;
    }
    for (size_t i = 0; i < word.size(); i++) {
        if (std::toupper(static_cast<unsigned char>(text[at + i])) != word[i]) {
            return false;
        }
    }
    return true;
}

// /WORD\s*(\d)/i: the first match's digit, or -1. With `one_to_four`,
// /WORD\s*([1-4])(?!\d)/i instead.
inline int word_digit(std::string_view text, std::string_view word, bool one_to_four) {
    for (size_t at = 0; at < text.size(); at++) {
        if (!word_at(text, at, word)) {
            continue;
        }
        size_t p = at + word.size();
        while (p < text.size() && is_space(text[p])) {
            p++;
        }
        if (p >= text.size() || !is_digit(text[p])) {
            continue;
        }
        int digit = text[p] - '0';
        if (one_to_four) {
            if (digit < 1 || digit > 4) {
                continue;
            }
            if (p + 1 < text.size() && is_digit(text[p + 1])) {
                continue;
            }
        }
        return digit;
    }
    return -1;
}

inline bool contains_word(std::string_view text, std::string_view word) {
    for (size_t at = 0; at < text.size(); at++) {
        if (word_at(text, at, word)) {
            return true;
        }
    }
    return false;
}

}  // namespace detail

// The address a chip goes to, by its file name (larc.js chipBase):
// SBCn at (n-1)*0x800, NVSn at 0x8000+(n-1)*0x1000, 224 ROMn (n = 1..4) at
// (n-1)*0x800. As the page, "SBC0" gives -0x800.
inline std::optional<int> chip_base(std::string_view name) {
    int d = detail::word_digit(name, "SBC", false);
    if (d >= 0) {
        return (d - 1) * 0x800;
    }
    d = detail::word_digit(name, "NVS", false);
    if (d >= 0) {
        return 0x8000 + (d - 1) * 0x1000;
    }
    d = detail::word_digit(name, "ROM", true);
    if (d >= 0) {
        return (d - 1) * 0x800;
    }
    return std::nullopt;
}

// The machine a set of chip file names belongs to (larc.js modelOf):
// 1 = the original 224 (ROM1-ROM4), 0 = the 224X/224XL (SBCn/NVSn).
inline int model_of(const std::vector<std::string> &names) {
    for (const std::string &name : names) {
        bool rom = detail::word_digit(name, "ROM", true) >= 0;
        bool sbc_nvs = detail::contains_word(name, "SBC") || detail::contains_word(name, "NVS");
        if (rom && !sbc_nvs) {
            return 1;
        }
    }
    return 0;
}

// The page's key for a set (app.js romHash, precompute.mjs romHash): the
// first 8 bytes of SHA-256 over the chips' bytes concatenated in base order,
// as 16 lower-case hex digits. Names page/catalogs/<hash>.json.
inline std::string catalog_hash(const std::vector<Chip> &chips_by_base) {
    Sha256 hash;
    for (const Chip &chip : chips_by_base) {
        hash.update(chip.bytes.data(), chip.bytes.size());
    }
    return Sha256::hex(hash.finish()).substr(0, 16);
}

// What kind of machine a set is, for its list entry (firmware.js describeSet).
inline std::string describe(const RomSet &set) {
    if (set.model == 1) {
        return "original 224, front panel";
    }
    int low = 0;
    for (const Chip &chip : set.chips) {
        if (chip.base < 0x8000) {
            low++;
        }
    }
    if (low >= 3) {
        return "224XL, LARC remote";
    }
    return "224X, front panel";
}

// The sets among `files` (firmware.js findSets): known complete sets first, in
// firmware_sets.json order, then one by-name set of the rest (if any file has
// a chip name). A file whose hash belongs to a found known set is "used" (so
// are its copies) and not placed again by name; among the rest, the first
// file per base wins (later ones are duplicates).
inline std::vector<RomSet> find_sets(const std::vector<Candidate> &files) {
    std::vector<std::string> hashes;
    hashes.reserve(files.size());
    std::map<std::string, size_t> by_hash;     // the last file with each hash, as the page's Map
    for (size_t i = 0; i < files.size(); i++) {
        hashes.push_back(Sha256::of(files[i].bytes.data(), files[i].bytes.size()));
        by_hash[hashes.back()] = i;
    }

    std::vector<RomSet> sets;
    std::set<std::string> used;
    for (int s = 0; s < data::known_set_count; s++) {
        const data::KnownSet &known = data::known_sets[s];
        bool complete = true;
        for (int c = 0; c < known.chip_count; c++) {
            if (by_hash.find(known.chips[c].sha256) == by_hash.end()) {
                complete = false;
                break;
            }
        }
        if (!complete) {
            continue;
        }
        RomSet set;
        set.name = known.name;
        set.model = known.model;
        set.known = true;
        if (known.unsupported != nullptr) {
            set.supported = false;
            set.unsupported = known.unsupported;
        }
        for (int c = 0; c < known.chip_count; c++) {
            const Candidate &file = files[by_hash[known.chips[c].sha256]];
            set.chips.push_back(Chip{known.chips[c].base, known.chips[c].sha256, file.origin, file.bytes});
            used.insert(known.chips[c].sha256);
        }
        sets.push_back(std::move(set));
    }

    std::vector<size_t> rest;
    for (size_t i = 0; i < files.size(); i++) {
        if (used.count(hashes[i]) == 0 && chip_base(files[i].name).has_value()) {
            rest.push_back(i);
        }
    }
    if (!rest.empty()) {
        RomSet set;
        set.name = unrecognized_set_name;
        std::vector<std::string> names;
        std::set<int> placed;
        for (size_t i : rest) {
            names.push_back(files[i].name);
            int base = *chip_base(files[i].name);
            if (placed.count(base) != 0) {
                continue;
            }
            placed.insert(base);
            if (base < 0 || size_t(base) + files[i].bytes.size() > address_space) {
                continue;
            }
            set.chips.push_back(Chip{unsigned(base), hashes[i], files[i].origin, files[i].bytes});
        }
        set.model = model_of(names);
        if (!set.chips.empty()) {
            sets.push_back(std::move(set));
        }
    }

    for (RomSet &set : sets) {
        std::stable_sort(set.chips.begin(), set.chips.end(),
                         [](const Chip &a, const Chip &b) { return a.base < b.base; });
        set.catalog_hash = catalog_hash(set.chips);
    }
    return sets;
}

// The first set, among `sets`, the page would choose on its own: the first
// supported one (app.js showSets(sets.find(set => !set.unsupported))).
inline const RomSet *first_supported(const std::vector<RomSet> &sets) {
    for (const RomSet &set : sets) {
        if (set.supported) {
            return &set;
        }
    }
    return nullptr;
}

// The set whose catalog hash is `hash` (a saved state's ROM-set key), or null.
inline const RomSet *by_catalog_hash(const std::vector<RomSet> &sets, std::string_view hash) {
    for (const RomSet &set : sets) {
        if (set.catalog_hash == hash) {
            return &set;
        }
    }
    return nullptr;
}

// Copy a set's chips into an engine (lexplug::Engine or anything with
// load(const uint8_t *, size_t, unsigned)). Construct the engine with set.model.
template <class EngineT>
void load_set(const RomSet &set, EngineT &engine) {
    for (const Chip &chip : set.chips) {
        engine.load(chip.bytes.data(), chip.bytes.size(), chip.base);
    }
}

}  // namespace lexplug::roms
