#!/usr/bin/env python3
"""Generate Verilog constants from the backplane contract (contracts/backplane_224x.json).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def bool_param(value: object) -> str:
    return "1" if bool(value) else "0"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("contract", type=Path)
    ap.add_argument("out", type=Path)
    args = ap.parse_args()

    contract = json.loads(args.contract.read_text(encoding="utf-8"))
    ports = contract["diagnostic_ports"]
    dab = contract["dab_conventions"]
    xreg = contract["xreg_ingress"]
    read_strobes = contract["diagnostic_read_strobes"]
    dport = contract["dport_selects"]
    aru_tc = contract["aru_tc_backplane"]

    lines = [
        "// Generated by tools/gen_backplane_contract.py.",
        "// Source: contracts/backplane_224x.json",
        "localparam [7:0] R7_PORT_OFST_LOW = 8'd%d;" % int(ports["e30_ofst_low"]),
        "localparam [7:0] R7_PORT_OFST_HIGH = 8'd%d;" % int(ports["e31_ofst_high"]),
        "localparam [7:0] R7_PORT_BUS_TEST = 8'd%d;" % int(ports["e32_bus_test"]),
        "localparam [7:0] R7_PORT_E33 = 8'd%d;" % int(ports["e33_status"]),
        "localparam [7:0] R7_PORT_E34 = 8'd%d;" % int(ports["e34_control"]),
        "localparam [7:0] R7_PORT_E35 = 8'd%d;" % int(ports["e35_monitor"]),
        "localparam [7:0] R7_PORT_XREG_LO = 8'd%d;" % int(ports["xreg_low"]),
        "localparam [7:0] R7_PORT_XREG_HI = 8'd%d;" % int(ports["xreg_high"]),
        "localparam integer R7_DAB_WRITE_COMPLEMENT_REQUIRED = %s;"
        % bool_param(dab["firmware_write_to_dab_is_complemented"]),
        "localparam integer R7_DAB_WSTB_ACTIVE_LOW = %s;"
        % bool_param(dab["dab_wstb_active_low"]),
        "localparam integer R7_XREG_DATA_DRIVE_REQUIRED = %s;"
        % bool_param(xreg["cpu_data_drive_required"]),
        "localparam integer R7_XREG_DAB_FACADE_REQUIRED = %s;"
        % bool_param(xreg["dab_facade_required_until_physical_source_found"]),
        "localparam integer R7_DEFAULT_READ_MRDC_ASSERTED = %s;"
        % bool_param(read_strobes["default"]["mrdc_asserted"]),
        "localparam integer R7_DEFAULT_READ_IORC_ASSERTED = %s;"
        % bool_param(read_strobes["default"]["iorc_asserted"]),
        "localparam integer R7_XREG_READBACK_MRDC_ASSERTED = %s;"
        % bool_param(read_strobes["xreg_readback"]["mrdc_asserted"]),
        "localparam integer R7_XREG_READBACK_IORC_ASSERTED = %s;"
        % bool_param(read_strobes["xreg_readback"]["iorc_asserted"]),
        "localparam integer R7_DPORT_SELECT_ACTIVE_LOW = %s;"
        % bool_param(dport["active_low"]),
        "localparam integer R7_SAT_ACTIVE_HIGH = %s;"
        % bool_param(aru_tc["sat_active_high"]),
        "localparam integer R7_ARUCKE_INVERTS_TC_ARUCK = %s;"
        % bool_param(aru_tc["arucke_inverts_tc_aruck"]),
        "localparam integer R7_M_BACKPLANE_ACTIVE_LOW = %s;"
        % bool_param(aru_tc["m0_m1_backplane_active_low"]),
        "localparam integer R7_CSIGN_ACTIVE_LOW = %s;"
        % bool_param(aru_tc["csign_active_low"]),
        "localparam integer R7_RDRREG_ACTIVE_LOW = %s;"
        % bool_param(aru_tc["rdrreg_active_low"]),
        "localparam integer R7_WA_RA_SELECTS_ACTIVE_LOW = %s;"
        % bool_param(aru_tc["wa_ra_selects_active_low"]),
        "",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
