#!/usr/bin/env python3
"""Write source/roms/firmware_sets_data.hpp from the web demo's firmware_sets.json.

The header carries only what the JSON carries: set names, models, chip bases,
SHA-256 digests and the "unsupported" reasons. Never ROM bytes.

  python3 tools/gen_firmware_sets.py            # from ../web-demo/page/firmware_sets.json
  python3 tools/gen_firmware_sets.py --check    # exit 1 if the header is stale
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent.parent / "web-demo" / "page" / "firmware_sets.json"
TARGET = HERE.parent / "source" / "roms" / "firmware_sets_data.hpp"


def c_string(text: str) -> str:
    return json.dumps(text, ensure_ascii=True)


def render(sets: list[dict]) -> str:
    lines = [
        "// GENERATED by tools/gen_firmware_sets.py from",
        "// web-demo/page/firmware_sets.json. Do not edit by hand.",
        "// Hashes and names only: never ROM bytes.",
        "#pragma once",
        "",
        "namespace lexplug::roms::data {",
        "",
        "struct KnownChip {",
        "    unsigned base;",
        "    const char *sha256;",
        "};",
        "",
        "struct KnownSet {",
        "    const char *name;",
        "    int model;                 // 0 = 224X/224XL, 1 = the original 224",
        "    const char *unsupported;   // nullptr when the set boots on the row machine",
        "    int chip_count;",
        "    KnownChip chips[16];",
        "};",
        "",
        "inline constexpr KnownSet known_sets[] = {",
    ]
    for s in sets:
        if len(s["chips"]) > 16:
            raise SystemExit(f"{s['name']}: more than 16 chips")
        reason = c_string(s["unsupported"]) if s.get("unsupported") else "nullptr"
        lines.append(f"    {{{c_string(s['name'])}, {int(s['model'])}, {reason}, {len(s['chips'])}, {{")
        for chip in s["chips"]:
            lines.append(f"        {{0x{int(chip['base']):04x}, \"{chip['sha256']}\"}},")
        lines.append("    }},")
    lines += [
        "};",
        "",
        "inline constexpr int known_set_count = int(sizeof(known_sets) / sizeof(known_sets[0]));",
        "",
        "}  // namespace lexplug::roms::data",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    text = render(json.loads(SOURCE.read_text()))
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text() != text:
            print(f"{TARGET} is stale; run tools/gen_firmware_sets.py")
            sys.exit(1)
        print("firmware_sets_data.hpp is up to date")
        return
    TARGET.write_text(text)
    print(f"wrote {TARGET}")


if __name__ == "__main__":
    main()
